Repository khurrumchaudhrty/MinarMarket_Development, pull requests merged in 2025-03, with the labels that each got.

#89 Editing Product Requirements fixed.
  backend/controllers/BuyerRequirementController.js
  backend/routes/BuyerRequirementRoutes.js
  minarmarket/components/proposal-list.jsx
  minarmarket/components/requirement-form.jsx
  minarmarket/lib/api/buyer-requirement.js
  minarmarket/lib/api/product.js
Labels: bug

#91 Categories Section is functional (on Buyer Dashboard)
  backend/controllers/ProductListingController.js
  backend/controllers/ServiceListingController.js
  backend/models/ServiceListing.js
  backend/routes/ProductListingRoutes.js
  backend/routes/ServiceListingRoutes.js
  minarmarket/app/app/dashboard/page.jsx
  minarmarket/components/service-form.jsx
  minarmarket/package-lock.json
  minarmarket/package.json
Labels: bug

#90 ServiceRequirements Form Edit Fixed
  backend/controllers/BuyerServiceRequirementController.js
  backend/routes/BuyerRequirementRoutes.js
  backend/routes/BuyerServiceRequirementRoutes.js
  minarmarket/components/requirement-form.jsx
  minarmarket/components/service-requirement-form.jsx
  minarmarket/lib/api/buyer-requirement.js
Labels: bug

#92 Landing Page is functional
  backend/controllers/ProductListingController.js
  backend/controllers/ServiceListingController.js
  backend/routes/ProductListingRoutes.js
  backend/routes/ServiceListingRoutes.js
  minarmarket/app/app/dashboard/page.jsx
  minarmarket/app/layout.jsx
  minarmarket/app/page.js
  minarmarket/app/page.jsx
  minarmarket/components/data-grid.jsx
Labels: bug

#94 Phone number required at the time of signup
  backend/controllers/UserAuthController.js
  backend/models/User.js
  minarmarket/app/signup/SignupForm.jsx
Labels: bug

#96 Message tiles show name and phone number
  backend/controllers/BuyerMessagesToSellers.js
  minarmarket/app/app/seller/buyers-messages/page.jsx
Labels: bug

#109 Admin can ban and suspend users.
  backend/controllers/BuyerProductRequirementController.js
  backend/controllers/ComplaintController.js
  backend/controllers/ProductListingController.js
  backend/controllers/ServiceListingController.js
  backend/models/BuyerRequirement.js
  backend/models/BuyerServiceRequirement.js
  backend/models/ProductListing.js
  backend/models/ServiceListing.js
  backend/models/User.js
  minarmarket/app/app/admin/reports/[id]/page.jsx
  minarmarket/app/page.jsx
  minarmarket/components/product-form.jsx
  minarmarket/components/service-form.jsx
  minarmarket/lib/api/admin.js
  minarmarket/lib/api/service.js
Labels: beta

#110 Fixed the problem
  minarmarket/components/site-header.jsx
  minarmarket/package-lock.json
Labels: enhancement

#111 Updated sign in button
  minarmarket/app/signin/login.jsx
Labels: enhancement

#112 About Us Created
  minarmarket/app/aboutus/aboutus.jsx
  minarmarket/app/aboutus/page.jsx
  minarmarket/components/site-header.jsx
Labels: enhancement

#113 New Contact Us Page
  minarmarket/app/contactus/contactus.jsx
  minarmarket/app/contactus/page.jsx
  minarmarket/components/site-header.jsx
Labels: enhancement

#114 Made 7 New Pages
  minarmarket/app/careers/careers.jsx
  minarmarket/app/careers/page.jsx
  minarmarket/app/community-guidelines/communityguide.jsx
  minarmarket/app/community-guidelines/page.jsx
  minarmarket/app/cookiepolicy/cookie.jsx
  minarmarket/app/cookiepolicy/page.jsx
  minarmarket/app/press/page.jsx
  minarmarket/app/press/press.jsx
  minarmarket/app/privacy/page.jsx
  minarmarket/app/privacy/privacypolicy.jsx
  minarmarket/app/safety-center/page.jsx
  minarmarket/app/safety-center/safety.jsx
  minarmarket/app/termsofservice/page.jsx
  minarmarket/app/termsofservice/termsofservice.jsx
  minarmarket/components/site-footer.jsx
  minarmarket/components/ui/tabs.jsx
Labels: enhancement

#116 Banned or Suspended User cannot log in now
  backend/controllers/UserAuthController.js
  minarmarket/app/signin/login.jsx
  minarmarket/components/site-header.jsx
Labels: beta

#118 Contact seller for service
  backend/controllers/BuyerMessages.js
  backend/controllers/BuyerMessagesToSellers.js
  backend/models/BuyerMessages.js
  minarmarket/app/app/individual-service/[id]/page.jsx
  minarmarket/app/app/seller/buyers-messages/page.jsx
  minarmarket/components/ContactSellerButton.jsx
Labels: beta

#121 Changed Dashboards
  minarmarket/app/app/dashboard/page.jsx
  minarmarket/components/data-grid.jsx
  minarmarket/components/header.jsx
  minarmarket/components/product-card.jsx
  minarmarket/components/sidebar-nav.jsx
  minarmarket/components/ui/sidebar.jsx
  minarmarket/package-lock.json
  minarmarket/package.json
Labels: enhancement

#125 Pagination done for seller and buyer side
  backend/controllers/BuyerMessagesToSellers.js
  backend/controllers/ProposalController.js
  backend/models/ProductListing.js
  backend/models/Proposal.js
  minarmarket/app/app/buyer/my-products/page.jsx
  minarmarket/app/app/seller/buyer-products/page.jsx
  minarmarket/app/app/seller/buyer-services/page.jsx
  minarmarket/app/app/seller/buyers-messages/page.jsx
  minarmarket/app/app/seller/my-services/page.jsx
  minarmarket/components/data-list.jsx
  minarmarket/components/proposal-list.jsx
  minarmarket/components/sent-proposal-list.jsx
Labels: beta

#130 Landing Page Fixed
  minarmarket/app/globals.css
  minarmarket/app/page.jsx
  minarmarket/components/site-footer.jsx
  minarmarket/components/site-header.jsx
Labels: enhancement

#132 New UI/UX for sigin/signup pages
  minarmarket/app/signin/login.jsx
  minarmarket/app/signup/SignupForm.jsx
Labels: enhancement
